# Generated by Django 5.0.1 on 2024-01-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.AddField(
            model_name='bus',
            name='FROM',
            field=models.CharField(default='devi', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='TO',
            field=models.CharField(default='appu', max_length=50),
        ),
    ]
